// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    XtxBread: typeof import('./components/library/xtx-bread.vue')['default']
    XtxBreadItem: typeof import('./components/library/xtx-bread-item.vue')['default']
    XtxButton: typeof import('./components/library/xtx-button.vue')['default']
    XtxCarousel: typeof import('./components/library/xtx-carousel.vue')['default']
    XtxCheckbox: typeof import('./components/library/xtx-checkbox.vue')['default']
    XtxCity: typeof import('./components/library/xtx-city.vue')['default']
    XtxConfirm: typeof import('./components/library/xtx-confirm.vue')['default']
    XtxInfiniteLoading: typeof import('./components/library/xtx-infinite-loading.vue')['default']
    XtxMessage: typeof import('./components/library/xtx-message.vue')['default']
    XtxMore: typeof import('./components/library/xtx-more.vue')['default']
    XtxNumber: typeof import('./components/library/xtx-number.vue')['default']
    XtxNumbox: typeof import('./components/library/xtx-numbox.vue')['default']
    XtxPagination: typeof import('./components/library/xtx-pagination.vue')['default']
    XtxSkeleton: typeof import('./components/library/xtx-skeleton.vue')['default']
  }
}
